### ISSUE TITLE
Could you clarify the "build" step in the README?

### ISSUE THREAD

**Issue by tvaughanRR** [runZeroInc/sshamble#3]
I'm not a "go" guy, so I'm not sure how to go from the example in your README of `go run main.go -h` (which works fine) to `sshamble scan -o ...`  (which fails with "sshamble: command not found")

It's assuming there's an `sshamble` on the path, but where/how did that happen?  Is there a `make` or `build` or `compile` step?  

Thanks!

**Comment by Slad3G** [comment]
Aa a temporary workaround you can run the commands as follows:

`go run main.go scan -o results.json 192.168.0.0/24`

`go run main.go analyze -o results-directory results.json`

Hope that helps.

S

**Comment by hdm** [comment]
thanks! clarified!
