### ISSUE TITLE
Seems to be failing for big subnets

### ISSUE THREAD

**Issue by nawabs11** [runZeroInc/sshamble#4]
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x18867ea60 m=2 sigcode=0

goroutine 0 gp=0x14000002a80 m=2 mp=0x14000062908 [idle]:
runtime: g 0 gp=0x14000002a80: unknown pc 0x18867ea60
stack: frame={sp:0x16e296bf0, fp:0x0} stack=[0x16da9b328,0x16e296f28)
0x000000016e296af0:  0x0000000000000000  0x000000016e296b98 
0x000000016e296b00:  0x0000000102398ed8 <runtime.(*mheap).allocManual+0x0000000000000028>  0x0000000000000000 
0x000000016e296b10:  0x0000000032aaaba2  0x0000000000000000 
0x000000016e296b20:  0x0000000000000000  0x0000000000000000 
0x000000016e296b30:  0x0000000000000000  0x0000000000000000 
0x000000016e296b40:  0x0000000000000000  0x0000000000000000 
....****

**Comment by hdm** [comment]
Can you share the CIDR size and the OS/architecture where you ran into this?

**Comment by nawabs11** [comment]
Tried running for a /20
Running on a MAC M1

**Comment by hdm** [comment]
A quick test of a /8 seems to work here as well:

```

👾 sshamble $ go run main.go scan 127.0.0.0/8
time="2024-08-09 09:07:36" level=info msg="scan processed 4066 tasks in 10s"
time="2024-08-09 09:07:41" level=info msg="scan processed 6619 tasks in 15s"
time="2024-08-09 09:07:46" level=info msg="scan processed 10689 tasks in 20s"
```

I think this may be some CGO sillyness.

Could you try building with CGO_ENABLED=0?

$ export CGO_ENABLED=0
$ go build -o sshamble

**Comment by nawabs11** [comment]
That works! Thanks
